swagger: "2.0"
info:
  description: "This is an sample webhook for Actions Google"
  version: "0.0.1"
  title: "Swagger Actions Google"
  termsOfService: "https://developers.google.com/actions/reference/rest/conversation-webhook"
  contact:
    email: "latorrefi@gmail.com"
host: "example.com"
tags:
- name: "Conversation"
  description: "Everything about conversation"
schemes:
- "https"
paths:
  /fulfillment:
    post:
      tags:
      - "Conversation"
      summary: "Handle a new intent"
      description: ""
      operationId: "fulfillment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "AppRequest"
        required: true
        schema:
          $ref: "#/definitions/AppRequest"
      responses:
        200:
          description: Timeline returned
          schema:
            type: array
            items:
              $ref: '#/definitions/AppResponse'
definitions:
  AppRequest:
    type: "object"
    properties:
      user:
        $ref: "#/definitions/User"
      device:
        $ref: "#/definitions/Device"
      surface:
        $ref: "#/definitions/Surface"
      conversation:
        $ref: "#/definitions/Conversation"
      inputs:
        type: array
        items:
          $ref: "#/definitions/Input"
      isInSandbox:
        type: "boolean"
        default: true
  AppResponse:
    type: "object"
  User:
    type: "object"
    properties:
      userId:
        type: string
      profile:
        $ref: '#/definitions/UserProfile'
      accessToken:
        type: string
      permissions:
        type: array
        items:
          $ref: '#/definitions/Permission'
      locale:
        type: string
      lastSeen:
        type: string
      userStorage:
        type: string
      packageEntitlements:
        type: array
        items:
          $ref: '#/definitions/PackageEntitlement'
  Device:
    type: "object"
  Surface:
    type: "object"
  Conversation:
    type: "object"
  Input:
    type: "object"
  UserProfile:
    type: "object"
    properties:
      displayName:
        type: string
      givenName:
        type: string
      familyName:
        type: string
  Permission:
    type: string
    enum:
      - UNSPECIFIED_PERMISSION
      - NAME
      - DEVICE_PRECISE_LOCATION
      - DEVICE_COARSE_LOCATION
      - UPDATE
  PackageEntitlement:
    type: "object"
    properties:
      packageName:
        type: string
      entitlements:
        type: array
        items:
          $ref: '#/definitions/Entitlement'
  Entitlement:
    type: "object"
    properties:
      sku:
        type: string
      skuType:
        type: string
        enum:
          - TYPE_UNSPECIFIED
          - IN_APP
          - SUBSCRIPTION
          - APP
      inAppDetails:
        $ref: '#/definitions/SignedData'
  SignedData:
    type: "object"
    properties:
      inAppPurchaseData:
        type: "object"
        additionalProperties:
          type: "object"
      inAppDataSignature:
        type: string
